### ISSUE TITLE
Wiki installation instructions: `pip install git+http://github.com/zandeez/twython-django.git` should be `pip install git+http://github.com/ryanmcgrath/twython-django.git`

### ISSUE THREAD

**Issue by dminkovsky** [ryanmcgrath/twython-django#3]

**Comment by dminkovsky** [comment]
Thanks Ryan. I've got some other ideas for the wiki, and can post some issues/suggestions. 

Thanks for the code!

**Comment by zandeez** [comment]
Just thought I'd weigh in for no reason, the install URL was probably left over from pulling in my code, no other changes have been made to either repo since so technically the two are equivalent anyway :)
