### ISSUE TITLE
__init__() got an unexpected keyword argument

### ISSUE THREAD

**Issue by ghost** [ryanmcgrath/twython-django#8]
twitter = Twython(
        twitter_token = settings.TWITTER_KEY,
        twitter_secret = settings.TWITTER_SECRET,
        callback_url = request.build_absolute_uri(reverse('XXX.views.thanks'))
    )

Hi. I was hoping someone could help me figure out what I'm doing wrong.

I run the above code. And I get this error message: "**init**() got an unexpected keyword argument 'callback_url'"

**Comment by ghost** [comment]
Never mind. I was using old documentation.

**Comment by nyanev** [comment]
How did you fix the problem?

**Comment by ghost** [comment]
Use the documentation here https://github.com/ryanmcgrath/twython as apposed to https://github.com/ryanmcgrath/twython-django/
