### ISSUE TITLE
Twython-django is not on pip?

### ISSUE THREAD

**Issue by rahanar** [ryanmcgrath/twython-django#9]
Hi,

I tried to install twython-django via pip but i get this error:

No distributions at all found for twython-django

I really need to be able to install via pip. 

Thank you

**Comment by nostalgiaz** [comment]
+1

$ pip install twython-django
Downloading/unpacking twython-django
Could not find any downloads that satisfy the requirement twython-django
No distributions at all found for twython-django

**Comment by michaelhelmick** [comment]
@ryanmcgrath has to publish it, unless he doesn't care that I add the package on PyPi.

Regardless, you can install the version that's on GitHub via pip:
`pip install git+ssh://git@github.com/ryanmcgrath/twython-django.git`

**Comment by ryanmcgrath** [comment]
I trust @michaelhelmick to handle this on Pypi should he decide he wishes to handle it. If not, I can't realistically handle this at this point in time, but I'll keep it in mind for the future.

**Comment by michaelhelmick** [comment]
Alright, cool. I’ll throw an official package up at the beginning of next week!  

## 

Mike Helmick
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by monajalal** [comment]
How should I install twython-django package?
@michaelhelmick  @ryanmcgrath 
sudo pip install twython-django
Downloading/unpacking twython-django
  Could not find any downloads that satisfy the requirement twython-django
No distributions at all found for twython-django
Storing complete log in /home/mona/.pip/pip.log

**Comment by michaelhelmick** [comment]
You could use the suggestion that I left above or can wait til Monday and there will be a version on Pypi to install via pip

—

**Comment by monajalal** [comment]
Hi,

 Do you have a wrapper for Twython and Postgres or Tython and HDFS?
 Something like this http://ryrobes.com/python/harvesting-twitter-search-results-for-analysis-using-python-sql-server/ which is for SQL Server.

Thanks,
Mona.

**Comment by michaelhelmick** [comment]
`twython-django` is now available on PyPi.

`pip install twython-django`

**Comment by ryanmcgrath** [comment]
+1
